### ISSUE TITLE
S3 Server - EACCES permission denied

### ISSUE THREAD

**Issue by matthewparkinsondes** [nestybox/sysbox#558]
os=ubuntu 20.04, kernel=5.18.2, docker=20.10.16, sysbox=0.5.2 EE, containerd=1.6.4, runc=1.1.1

docker run --runtime=sysbox-runc -d --restart always -p8000:8000 --name s3server scality/s3server

{"name":"DataFileStore","time":1654547614619,"error":{"errno":-13,"code":"EACCES","syscall":"access","path":"/usr/src/app/lib/../localData"},"level":"error","message":"Data path is not readable or writable","hostname":"7f910a099231","pid":148}
{"name":"S3","time":1654547614621,"error":{"errno":-13,"code":"EACCES","syscall":"access","path":"/usr/src/app/lib/../localData"},"level":"error","message":"Error initializing REST data server","hostname":"7f910a099231","pid":148}
fs.js:250
  binding.access(pathModule._makeLong(path), mode);
          ^

Error: EACCES: permission denied, access '/usr/src/app/lib/../localMetadata'
    at Error (native)
    at Object.fs.accessSync (fs.js:250:11)
    at MetadataFileServer.startServer (/usr/src/app/node_modules/arsenal/lib/storage/metadata/file/MetadataFileServer.js:124:12)
    at Object.<anonymous> (/usr/src/app/mdserver.js:17:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

**Comment by rodnymolina** [comment]
As discussed with @matthewparkinsondes through slack, at first glance this issue seems to be kernel specific as we are not able to reproduce it in previous kernel releases while matching all other variables.
