### ISSUE TITLE
sysbox-fs.service Runtime Panic: Recurring Index Out of Range Error

### ISSUE THREAD

**Issue by abhinav-kodekloud** [nestybox/sysbox#890]
**Issue Description:**
The sysbox-fs service is experiencing recurring runtime panics due to an index out of range error in the seccomp memory parsing component

**Detailed Error Trace**
```shell
Dec 17 12:39:59 delta-exam-worker3 sysbox-fs[25514]: panic: runtime error: index out of range [0] with length 0
Dec 17 12:39:59 delta-exam-worker3 sysbox-fs[25514]: goroutine 14963551 [running]:
Dec 17 12:39:59 delta-exam-worker3 sysbox-fs[25514]: github.com/nestybox/sysbox-fs/seccomp.(*memParserIOvec).readProcessMem(0x203000?, 0xc188e, {0xc0000b5bc0, 0x1, 0x0?}, {0xc0000b5b90, 0x1, 0xc000101800?}, {0xc0000b5b88, 0x1, ...})
Dec 17 12:39:59 delta-exam-worker3 sysbox-fs[25514]:         github.com/nestybox/sysbox-fs/seccomp/memParserIOvec.go:99 +0x345
Dec 17 12:39:59 delta-exam-worker3 sysbox-fs[25514]: github.com/nestybox/sysbox-fs/seccomp.(*memParserIOvec).ReadSyscallBytesArgs(0xc000c162d0?, 0x0?, {0xc000d2b1a0?, 0x1, 0x40f347?})
Dec 17 12:39:59 delta-exam-worker3 sysbox-fs[25514]:         github.com/nestybox/sysbox-fs/seccomp/memParserIOvec.go:63 +0x1b7
Dec 17 12:39:59 delta-exam-worker3 sysbox-fs[25514]: github.com/nestybox/sysbox-fs/seccomp.(*syscallTracer).processSetxattr(0xc000142380, 0xc001100200, 0xbd?, {0xbed108, 0xc000126400}, {0xafffce, 0x9})
Dec 17 12:39:59 delta-exam-worker3 sysbox-fs[25514]:         github.com/nestybox/sysbox-fs/seccomp/tracer.go:833 +0x1b8
Dec 17 12:39:59 delta-exam-worker3 sysbox-fs[25514]: github.com/nestybox/sysbox-fs/seccomp.(*syscallTracer).processSyscall(0xc000142380, 0xc001100200, 0x0?, {0xc000cbc540, 0x40})
Dec 17 12:39:59 delta-exam-worker3 sysbox-fs[25514]:         github.com/nestybox/sysbox-fs/seccomp/tracer.go:497 +0x4ab
Dec 17 12:39:59 delta-exam-worker3 sysbox-fs[25514]: github.com/nestybox/sysbox-fs/seccomp.(*syscallTracer).process(0xc000142380, 0xc001100200, 0x596f40?, {0xc000cbc540, 0x40})
Dec 17 12:39:59 delta-exam-worker3 sysbox-fs[25514]:         github.com/nestybox/sysbox-fs/seccomp/tracer.go:439 +0xb0
Dec 17 12:39:59 delta-exam-worker3 sysbox-fs[25514]: created by github.com/nestybox/sysbox-fs/seccomp.(*syscallTracer).connHandler
Dec 17 12:39:59 delta-exam-worker3 sysbox-fs[25514]:         github.com/nestybox/sysbox-fs/seccomp/tracer.go:420 +0x4b5
Dec 17 12:39:59 delta-exam-worker3 systemd[1]: sysbox-fs.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 17 12:39:59 delta-exam-worker3 systemd[1]: sysbox-fs.service: Failed with result 'exit-code'.
```

**Frequency**
- This error occurs frequently, causing sysbox-fs to crash 2-3 times a day
- Results in service failure with exit code 2 (INVALIDARGUMENT)

**Potential Impact**
- Disrupts the ongoing sessions on the worker nodes (on which sysbox installed)
- Disrupts the worker nodes
- Causes unexpected service terminations

**Setup**
- Sysbox version: 0.6.1
- CRI-O version: 1.26.4
- Kubernets Version: 1.26.0

**Comment by ctalledo** [comment]
Fixed in Sysbox v0.6.5 via [this commit](https://github.com/nestybox/sysbox-fs/commit/a4875f9b23a2e97d60a2bbeaeded28b97d38c8ac).
